- name: Check cp-serviceability replica set number
  shell:
    cmd: "oc get rs -n {{ gi_namespace }} | grep cp-serviceability | wc -l"
  register: cp_rs_number

- name: Remove redundant replica set
  shell:
    cmd: "[ `oc get rs -n {{ gi_namespace }} | grep cp-serviceability | awk '{ print $2$3$4 }'` == '111' ] && echo `oc delete rs -n {{ gi_namespace }} | grep cp-serviceability | awk '{ print $1 }'`"
  when: cp_rs_number.stdout|int == 2

- name: Check GI deployment status
  shell:
    cmd: "oc get guardiuminsights -n {{ gi_namespace }} -o json|jq .items[0].status.versions.reconciled|tr -d '\"'"
  register: gi_deployment_status
