- hosts: bastion
  vars:
    internet_type: "{{ lookup('env','GI_INTERNET_ACCESS') }}"
    bas_ip: "{{ lookup('env','GI_BASTION_IP') }}"
    ntp_server: "{{ lookup('env','GI_NTP_SRV') }}"

  vars_files:
    - constants.yaml

  tasks:
    - name: Check standard configuration parameters
      ansible.builtin.fail: msg="Variable {{ item.name }} is not set"
      when: item.value == ""
      loop:
        - { name: "GI_INTERNET_ACCESS", value: "{{ internet_type }}" }
        - { name: "GI_BASTION_IP", value: "{{ bas_ip }}" }
        - { name: "GI_NTP_SRV", value: "{{ ntp_server }}" }

    - name: Setup bastion
      ansible.builtin.include_tasks: bastion_setup.yaml
      when: skip_phase|int < 1
