- hosts: bastion
  vars:
    internet_type: "{{ lookup('env','GI_INTERNET_ACCESS') }}"
    bas_ip: "{{ lookup('env','GI_BASTION_IP') }}"
    ntp_server: "{{ lookup('env','GI_NTP_SRV') }}"
    ocp_release: "{{ lookup('env','GI_OCP_RELEASE') }}"
    ocp_major_release: "{{ ocp_release.split('.')[:-1]|join('.') }}"
    ocp_minor_release: "{{ ocp_release.split('.')[-1] }}"
    boot_name: "{{ lookup('env','GI_BOOTSTRAP_NAME') }}"
    boot_ip: "{{ lookup('env','GI_BOOTSTRAP_IP') }}"
    boot_mac: "{{ lookup('env','GI_BOOTSTRAP_MAC_ADDRESS') }}"
    master_ip: "{{ lookup('env', 'GI_MASTER_IP').split(',') }}"
    master_mac: "{{ lookup('env', 'GI_MASTER_MAC_ADDRESS').split(',') }}"
    master_name: "{{ lookup('env', 'GI_MASTER_NAME').split(',') }}"
    is_master_only: "{{ lookup('env','GI_MASTER_ONLY') }}"
    is_ocs_tainted: "{{ lookup('env','GI_OCS_TAINTED') }}"
    ocp_domain: "{{ lookup('env','GI_DOMAIN') }}"
    boot_disk: "{{ lookup('env','GI_BOOT_DEVICE') }}"
    bas_int: "{{ lookup('env','GI_NETWORK_INTERFACE') }}"
    bas_name: "{{ lookup('env','GI_BASTION_NAME') }}"

  vars_files:
    - constants.yaml

  tasks:
    - name: Check standard configuration parameters
      ansible.builtin.fail: msg="Variable {{ item.name }} is not set"
      loop:
        - { name: "GI_INTERNET_ACCESS", value: "{{ internet_type }}" }
        - { name: "GI_BASTION_IP", value: "{{ bas_ip }}" }
        - { name: "GI_NTP_SRV", value: "{{ ntp_server }}" }
        - { name: "GI_OCP_RELEASE", value: "{{ ocp_release }}" }
        - { name: "GI_BOOTSTRAP_NAME", value: "{{ boot_name }}" }
        - { name: "GI_BOOTSTRAP_IP", value: "{{ boot_ip }}" }
        - { name: "GI_BOOTSTRAP_MAC_ADDRESS", value: "{{ boot_mac }}" }
        - { name: "GI_MASTER_IP", value: "{{ master_ip }}" }
        - { name: "GI_MASTER_MAC_ADDRESS", value: "{{ master_mac }}" }
        - { name: "GI_MASTER_NAME", value: "{{ master_name }}" }
        - { name: "GI_MASTER_ONLY", value: "{{ is_master_only }}" }
        - { name: "GI_OCS_TAINTED", value: "{{ is_ocs_tainted }}" }
        - { name: "GI_DOMAIN", value: "{{ ocp_domain }}" }
        - { name: "GI_BOOT_DEVICE", value: "{{ boot_disk }}" }
        - { name: "GI_NETWORK_INTERFACE", value: "{{ bas_int }}" }
        - { name: "GI_BASTION_NAME", value: "{{ bas_name }}" }
      when: item.value == ""

    - name: Set parameters for ntp set on bastion
      ansible.builtin.set_fact:
        ntp_clients: "{{ lookup('env','GI_NTP_CLIENTS') }}"
      when: ntp_server == bas_ip

    - name: Check parameters for ntp set on bastion
      ansible.builtin.fail: msg="Variable {{ item.name }} is not set"
      loop:
        - { name: "GI_NTP_CLIENTS", value: "{{ ntp_clients }}" }
      when: ntp_server == bas_ip and item.value == ""

    - name: Set worker nodes array
      ansible.builtin.set_fact:
        worker_ip: "{{ lookup('env', 'GI_WORKER_IP').split(',') }}"
        worker_mac: "{{ lookup('env', 'GI_WORKER_MAC_ADDRESS').split(',') }}"
        worker_name: "{{ lookup('env', 'GI_WORKER_NAME').split(',') }}"
      when: is_master_only == 'N'

    - name: Check workers configuration
      ansible.builtin.fail: msg="Variable {{ item.name }} is not set"
      loop:
        - { name: "GI_WORKER_IP", value: "{{ worker_ip }}" }
        - { name: "GI_WORKER_MAC_ADDRESS", value: "{{ worker_mac }}" }
        - { name: "GI_WORKER_NAME", value: "{{ worker_name }}" }
      when: is_master_only == 'N' and item.value == ""

    - name: Set ODF tainted nodes array
      ansible.builtin.set_fact:
        ocs_ip: "{{ lookup('env', 'GI_OCS_IP').split(',') }}"
        ocs_mac: "{{ lookup('env', 'GI_OCS_MAC_ADDRESS').split(',') }}"
        ocs_name: "{{ lookup('env', 'GI_OCS_NAME').split(',') }}"
      when: is_ocs_tainted == 'Y'

    - name: Check OCS configuration
      ansible.builtin.fail: msg="Variable {{ item.name }} is not set"
      loop:
        - { name: "GI_OCS_IP", value: "{{ ocs_ip }}" }
        - { name: "GI_OCS_MAC_ADDRESS", value: "{{ ocs_mac }}" }
        - { name: "GI_OCS_NAME", value: "{{ ocs_name }}" }
      when: is_ocs_tainted == 'Y' and item.value == ""

    - name: Setup bastion
      ansible.builtin.include_tasks: bastion_setup.yaml
      when: skip_phase|int < 1

