- hosts: bastion
  vars:
    internet_type: "{{ lookup('env','GI_INTERNET_ACCESS') }}"

  vars_files:
    - constants.yaml

  tasks:
    - name: Check standard configuration parameters
      ansible.builtin.fail: msg="Variable {{ item.name }} is not set"
      when: item.value == ""
      loop:
        - { name: "GI_INTERNET_ACCESS", value: "{{ internet_type }}" }

    - name: Setup bastion
      ansible.builtin.include_tasks: bastion_setup.yaml
      when: skip_phase|int < 1
