- name: Waiting for OCP cluster deployment (it takes 15-40 minutes)
  ansible.builtin.command: openshift-install --dir=../ocp wait-for bootstrap-complete

- name: Check bootstrap availability
  ansible.builtin.command:
    cmd: "ping -c 1 {{ boot_name }}.{{ ocp_domain }}"
  register: boot_availability
  ignore_errors: yes

- name: Stop bootstrap
  ansible.builtin.shell:
    cmd: "ssh -l core {{ boot_name }}.{{ ocp_domain }} -i {{ ssh_key }} sudo shutdown -h +1"
  remote_user: core
  when: boot_availability.rc != 2 and boot_availability.rc != 1

- name: Wait for boostrap shutdown
  ansible.builtin.pause:
    minutes: 1
  when: boot_availability.rc != 2 and boot_availability.rc != 1

- name: Remove DNS records
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: "{{ item.regexp }}"
    state: absent
  with_items:
    - { regexp: "^address=/matchbox." }
    - { regexp: "^address=/boot." }
    - { regexp: "^#TFTP" }
    - { regexp: "^tftp-" }
    - { regexp: "^enable-tftp" }
    - { regexp: "^dhcp-match" }
    - { regexp: "^dhcp-boot" }
    - { regexp: "^dhcp-userclass" }

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: Stop unused services
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: stopped
    enabled: no
  with_items:
    - { name: "matchbox" }

- name: Reconfigure HA Proxy
  ansible.builtin.lineinfile:
    path: /etc/haproxy/haproxy.cfg
    regexp: "{{ item.regexp }}"
    state: absent
  with_items:
    - { regexp: '^ server m0' }

- name: Restart HA Proxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: yes

- name: Copy HA Proxy config file
  ansible.builtin.copy:
    src: /etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg.main

- name: Check cluster nodes health and approve CSR's if needed
  ansible.builtin.shell: ../funcs/scripts/check_cluster_health.sh
  vars:
    node_number: "{{ master_ip|length+worker_ip|default([])|length+odf_ip|default([])|length }}"
  register: cluster_health
  until: node_number == cluster_health.stdout
  retries: 150
  delay: 10

- name: Wait for cluster operators
  ansible.builtin.shell:
    cmd: "oc get co --no-headers|awk '{ print $3$4$5 }'|grep -v TrueFalseFalse|wc -l"
  register: co_status
  until: "co_status.stdout == \"0\""
  retries: 150
  delay: 10

- name: Is htpasswd secret available
  ansible.builtin.shell:
    cmd: "oc get secret htpass-secret -n openshift-config -oname|wc -l"
  register: is_htpasswd_secret

- name: Create htpasswd file
  community.general.htpasswd:
    path: "{{ temp_dir }}/files/ocpadmin.htpasswd"
    name: "{{ ocpadmin }}"
    password: "{{ ocpadmin_password }}"
  when: is_htpasswd_secret.stdout|int == 0

- name: Register htpasswd secret for OCP admin
  ansible.builtin.shell:
    cmd: "{{ item.cmd }}"
  with_items:
    - { cmd: "oc create secret generic htpass-secret --from-file=htpasswd={{ temp_dir }}/files/ocpadmin.htpasswd -n openshift-config" }
  when: is_htpasswd_secret.stdout|int == 0

- name: Register htpasswd oauth provider
  ansible.builtin.shell:
    cmd: "{{ item.cmd }}"
  with_items:
    - { cmd: "oc apply -f ../funcs/yamls/oauth_provider.yaml" }
    - { cmd: "oc adm policy add-cluster-role-to-user cluster-admin {{ ocpadmin }}" }

- name: Wait a while before htpasswd secret will be registered
  ansible.builtin.pause:
    minutes: 1

- meta: end_play

- name: Disable default image sources
  ansible.builtin.shell:
    cmd: "oc patch OperatorHub cluster --type json -p '[{\"op\": \"add\", \"path\": \"/spec/disableAllDefaultSources\", \"value\": true}]'"
  when: internet_type == 'A'

- name: Wait to initiate changes related to added admin
  ansible.builtin.pause:
    minutes: 3
  when: is_htpasswd_secret.stdout|int == 0

- name: Configure imagecontentsourcepolicy file
  ansible.builtin.command:
    cmd: "sed -i 's/-.*:5000/- registry.{{ ocp_domain }}:5000/g' {{ temp_dir }}/archives/{{ item }}"
  with_items:
    - imageContentSourcePolicy.yaml
  when: internet_type == 'A'

- name: Configure catalogsource file
  ansible.builtin.command:
    cmd: "sed -i 's/image:.*:5000/image: registry.{{ ocp_domain }}:5000/g' {{ temp_dir }}/archives/{{ item }}"
  with_items:
    - catalogSource-redhat-operator-index.yaml
  when: internet_type == 'A'

- name: Set OLM operators catalog and OLM image content source policy"
  ansible.builtin.command:
    cmd: "oc apply -f {{ temp_dir }}/archives/{{ item }}"
  with_items:
    - imageContentSourcePolicy.yaml
    - catalogSource-redhat-operator-index.yaml
  when: internet_type == 'A'

- name: Configure rook-ceph imagecontentsourcepolicy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "rook_icsp.j2", dest: "{{ temp_dir }}/yamls/rook_icsp.yaml" }
  when: internet_type == 'A' and storage_type == 'R'

- name: Configure imageContentSourcePolicy for rook-ceph
  ansible.builtin.shell:
    cmd: "oc apply -f {{ temp_dir }}/yamls/{{ item }}"
  with_items:
    - rook_icsp.yaml
  when: internet_type == 'A' and storage_type == 'R'

- name: Configure openldap imagecontentsourcepolicy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "openldap_icsp.j2", dest: "{{ temp_dir }}/yamls/openldap_icsp.yaml" }
  when: internet_type == 'A' and install_ldap == 'Y'

- name: Apply imageContentSourcePolicy for openldap
  ansible.builtin.shell:
    cmd: "oc apply -f {{ temp_dir }}/yamls/{{ item }}"
  with_items:
    - openldap_icsp.yaml
  when: internet_type == 'A' and install_ldap == 'Y'

- name: Configure nfs-provisioner imagecontentsourcepolicy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "nfs_provisioner_icsp.j2", dest: "{{ temp_dir }}/yamls/nfs_provisioner_icsp.yaml" }
  when: internet_type == 'A' and gi_nfs_backup == 'Y'

- name: Apply imageContentSourcePolicy for nfs-provisioner
  ansible.builtin.shell:
    cmd: "oc apply -f {{ temp_dir }}/yamls/{{ item }}"
  with_items:
    - nfs_provisioner_icsp.yaml
  when: internet_type == 'A' and gi_nfs_backup == 'Y'

- name: Check cluster nodes health after Content Source Policy change
  ansible.builtin.shell: ../funcs/scripts/check_cluster_health_operators.sh
  register: cluster_health_operators
  until: cluster_health_operators.stdout == "0"
  retries: 200
  delay: 10
  when: internet_type == 'A'

- name: Wait for cluster operators after mirrored operator images setup (can take 20-40 minutes)
  ansible.builtin.shell:
      cmd: "oc get co --no-headers|awk '{ print $3$4$5 }'|grep -v TrueFalseFalse|wc -l"
  register: co_status
  until: "co_status.stdout == \"0\""
  retries: 150
  delay: 10
  when: internet_type == 'A'

- name: Add CM with new CA cert
  ansible.builtin.shell:
    cmd: "oc create configmap gn-ca --from-file=ca-bundle.crt={{ ocp_ca }} -n openshift-config"
  when: ocp_ext_ingress == 'Y'

- name: Add CA cert to OCP proxy configuration
  ansible.builtin.shell:
    cmd: "oc patch proxy/cluster --type=merge -p '{\"spec\":{\"trustedCA\":{\"name\":\"gn-ca\"}}}'"
  when: ocp_ext_ingress == 'Y'

- name: Wait for cluster stabilization - CA cert added
  ansible.builtin.pause:
    minutes: 5
  when: ocp_ext_ingress == 'Y'

- name: Check cluster nodes health after proxy certificate change
  ansible.builtin.shell: ../funcs/scripts/check_cluster_health_operators.sh
  register: cluster_health_operators
  until: cluster_health_operators.stdout == "0"
  retries: 150
  delay: 10
  when: ocp_ext_ingress == 'Y'

- name: Add secret with new cert
  ansible.builtin.shell:
    cmd: "oc create secret tls gncert --cert={{ ocp_cert }} --key={{ ocp_key }} -n openshift-ingress"
  when: ocp_ext_ingress == 'Y'

- name: Modify certificate for ingress
  ansible.builtin.shell:
    cmd: "oc patch ingresscontroller.operator default --type=merge -p '{\"spec\":{\"defaultCertificate\": {\"name\": \"gncert\"}}}' -n openshift-ingress-operator"
  when: ocp_ext_ingress == 'Y'

- name: Wait for cluster stabilization - cluster cert changed
  ansible.builtin.pause:
    minutes: 3
  when: ocp_ext_ingress == 'Y'

- name: Check cluster nodes health after ingress change
  ansible.builtin.shell: ../funcs/scripts/check_cluster_health_operators.sh
  register: cluster_health_operators
  until: cluster_health_operators.stdout == "0"
  retries: 150
  delay: 10
  when: ocp_ext_ingress == 'Y'

