- hosts: bastion
  vars:
    ocp_domain: "{{ lookup('env','GI_DOMAIN') }}"

  vars_files:
  - constants.yaml

  tasks:
  - name: Check configuration parameters
    fail: msg="Variable {{ item.name }} is not set"
    when: item.value == ""
    loop:
      - { name: "GI_DOMAIN", value: "{{ ocp_domain }}" }

  - name: Delete CPFS CSV in ibm-common-services
    shell:
      cmd: "[[ 'oc get csv -n ibm-common-services -oname | grep ibm-common-service-operator' ]] || oc delete $(oc get csv -n ibm-common-services -oname | grep ibm-common-service-operator) -n ibm-common-services"

  - name: Delete operand requests
    shell:
      cmd: "[[ 'oc get operandrequest -n ibm-common-services -oname' ]] || oc delete $(oc get operandrequest -n ibm-common-services -oname) -n ibm-common-services"

  - name: Wait for cleanup
    pause:
      minutes: 2

  - name: Wait for operand requests removal
    shell:
      cmd: "oc get pods -n ibm-common-services --no-headers|grep -v -e Running -e Completed|wc -l"
    register: cpfs_pods
    until: "cpfs_pods.stdout == \"0\""
    retries: 60
    delay: 10

  - name: Relogin to OCP
    shell:
      cmd: ../funcs/scripts/login_to_ocp.sh

  - name: Delete operand configs
    shell:
      cmd: "[[ 'oc get operandconfig -n ibm-common-services -oname' ]] || oc delete $(oc get operandconfig -n ibm-common-services -oname) -n ibm-common-services"

  - name: Delete operand registries
    shell:
      cmd: "oc delete $(oc get operandregistry -n ibm-common-services -oname) -n ibm-common-services --ignore-not-found"

  - name: Delete operand registries
    shell:
      cmd: "oc delete $(oc get namespacescope -n ibm-common-services -oname) -n ibm-common-services --ignore-not-found"

  - name: Delete CSV's
    shell:
      cmd: "oc delete $(oc get csv -n ibm-common-services -oname) -n ibm-common-services --ignore-not-found"

  - name: Delete subscriptions
    shell:
      cmd: "oc delete $(oc get sub -n ibm-common-services -oname) -n ibm-common-services --ignore-not-found"

  - name: Delete CSV's in common-service namespace
    shell:
      cmd: "oc delete $(oc get csv -n common-service -oname) -n common-service --ignore-not-found"

  - name: Delete webhooks
    shell:
      cmd: "{{ item }}"
    with_items:
      - oc delete ValidatingWebhookConfiguration cert-manager-webhook ibm-cs-ns-mapping-webhook-configuration --ignore-not-found
      - oc delete MutatingWebhookConfiguration cert-manager-webhook ibm-common-service-webhook-configuration ibm-operandrequest-webhook-configuration namespace-admission-config --ignore-not-found




