- hosts: bastion
  vars:
    ocp_domain: "{{ lookup('env','GI_DOMAIN') }}"

  vars_files:
  - constants.yaml

  tasks:
  - name: Check configuration parameters
    fail: msg="Variable {{ item.name }} is not set"
    when: item.value == ""
    loop:
      - { name: "GI_DOMAIN", value: "{{ ocp_domain }}" }

  - name: Check connection to API
    shell:
      cmd: "oc get nodes|wc -l"
    register: nodes_count
    failed_when: nodes_count.stdout|int < 1

  - name: Delete CPFS CSV in ibm-common-services
    shell:
      cmd: "[ $(oc get csv -n ibm-common-services -oname | grep ibm-common-service-operator | wc -l) -eq 1 ] && oc delete $(oc get csv -n ibm-common-services -oname | grep ibm-common-service-operator) -n ibm-common-services || echo 0"

  - name: Delete operand requests
    shell:
      cmd: "[ $(oc get operandrequest -n ibm-common-services -oname | wc -l) -ne 0 ] && oc delete $(oc get operandrequest -n ibm-common-services -oname) -n ibm-common-services || echo 0"

  - name: Wait for cleanup
    pause:
      minutes: 5

  - name: Relogin to OCP
    shell:
      cmd: ../funcs/scripts/login_to_ocp.sh

  - name: Wait for operand requests removal
    shell:
      cmd: "oc get pods -n ibm-common-services --no-headers|grep -v -e Running -e Completed|wc -l"
    register: cpfs_pods
    until: "cpfs_pods.stdout == \"0\""
    retries: 60
    delay: 10

  - name: Check connection to API
    shell:
      cmd: "oc get nodes|wc -l"
    register: nodes_count
    failed_when: nodes_count.stdout|int < 1

  - name: Delete operand configs
    shell:
      cmd: "[ $(oc get operandconfig -n ibm-common-services -oname | wc -l) -ne 0 ] && oc delete $(oc get operandconfig -n ibm-common-services -oname) -n ibm-common-services || echo 0"

  - name: Delete operand registries
    shell:
      cmd: "[ $(oc get operandregistry -n ibm-common-services -oname | wc -l) -ne 0 ] && oc delete $(oc get operandregistry -n ibm-common-services -oname) -n ibm-common-services || echo 0"

  - name: Delete operand registries
    shell:
      cmd: "[ $(oc get namespacescope -n ibm-common-services -oname | wc -l) -ne 0 ] && oc delete $(oc get namespacescope -n ibm-common-services -oname) -n ibm-common-services || echo 0"

  - name: Delete CSV's
    shell:
      cmd: "[ $(oc get csv -n ibm-common-services -oname | wc -l) -ne 0 ] && oc delete $(oc get csv -n ibm-common-services -oname) -n ibm-common-services || echo 0"

  - name: Delete subscriptions
    shell:
      cmd: "[ $(oc get sub -n ibm-common-services -oname | wc -l) -ne 0 ] && oc delete $(oc get sub -n ibm-common-services -oname) -n ibm-common-services || echo 0"

  - name: Delete CSV's in common-service namespace
    shell:
      cmd: "[ $(oc get csv -n common-service -oname | wc -l) -ne 0 ] && oc delete $(oc get csv -n common-service -oname) -n common-service || echo 0"

  - name: Delete configmap
    shell:
      cmd: "[ $(oc -n kube-public get configmap ibm-common-services-status | wc -l) -ne 0 ] && oc -n kube-public delete configmap ibm-common-services-status || echo 0"

  - name: Delete webhooks
    shell:
      cmd: "{{ item }}"
    with_items:
      - oc delete ValidatingWebhookConfiguration cert-manager-webhook ibm-cs-ns-mapping-webhook-configuration --ignore-not-found
      - oc delete MutatingWebhookConfiguration cert-manager-webhook ibm-common-service-webhook-configuration ibm-operandrequest-webhook-configuration namespace-admission-config --ignore-not-found

  - name: Delete namespaces
    shell:
      cmd: "oc delete namespace {{ item }} --ignore-not-found"
    with_items:
      - ibm-common-services
      - common-service
        
  - debug:
      msg:
      - "Cloud Pak Foundational services uninstalled with success."



