#Global variables
declare -a gi_versions=(3.2.10 3.2.11)
gi_32_threshold=3
declare -a ics_versions=(3.19.17)
declare -a ics_cases=(ibm-cp-common-services-1.15.17.tgz)
declare -a gi_cases=(ibm-guardium-insights-2.2.10.tgz ibm-guardium-insights-2.2.11.tgz)
declare -a bundled_in_gi_ics_versions=(0 0)
declare -a ocp_versions=(0 1)
declare -a ocp_major_versions=(4.10 4.12)
declare -a ocp_supported_by_gi=(0:1 0:1)
declare -a ocp_supported_by_ics=(0:1)
declare -a ocp_supported_by_cp4s="0:1"
declare -a gi_sizes=(values-dev values-small)
declare -a fedora_supp_releases=(38)
registry_version=2.8.1
rook_version="v1.9.9"
rook_sc=("rook-cephfs" "rook-ceph-block")
ocs_sc=("ocs-storagecluster-cephfs" "ocs-storagecluster-ceph-rbd")
galaxy_community_general="4.8.1"
galaxy_ansible_utils="2.6.1"
galaxy_community_crypto="2.3.4"
galaxy_containers_podman="1.9.3"
matchbox_version="0.10.0"
cp4s_channel="1.10"
declare -a cp4s_versions=(1.10.3)
declare -a cp4s_cases=(ibm-cp-security-1.0.28.tgz)
GI_HOME=`pwd`
GI_TEMP=$GI_HOME/gi-temp
file=$GI_HOME/variables.sh

