kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: registry
 namespace: openshift-image-registry
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 150Gi
 storageClassName: rook-cephfs

