- name: Set digests for images in order
  ansible.builtin.shell:
    cmd: "IFS=',' read -r -a rook_v_oper <<< `cat {{ temp_dir }}/rook/rook_images_sha|grep {{ item }}`;echo \"`echo ${rook_v_oper[1]}|awk -F '/' '{print $NF}'|awk -F':' '{print $1}'`@${rook_v_oper[2]}\""
  register: rook_digests
  with_items:
    - ROOK_CEPH_OPER
    - ROOK_CEPH_IMAGE
    - ROOK_CSI_CEPH_IMAGE
    - ROOK_CSI_REGISTRAR_IMAGE
    - ROOK_CSI_RESIZER_IMAGE
    - ROOK_CSI_PROVISIONER_IMAGE
    - ROOK_CSI_SNAPSHOTTER_IMAGE
    - ROOK_CSI_ATTACHER_IMAGE
    - CSI_VOLUME_REPLICATION_IMAGE
  when: internet_type == 'A'

